const {
  Client,
  GatewayIntentBits,
  REST,
  Routes,
  SlashCommandBuilder
} = require("discord.js");

const fs = require("fs");
const fetch = require("node-fetch");
const math = require("mathjs");

const client = new Client({
  intents: [GatewayIntentBits.Guilds]
});

const TOKEN = process.env.TOKEN;
const CLIENT_ID = process.env.CLIENT_ID;
const OPENAI_API_KEY = process.env.OPENAI_API_KEY;

// ===== DATABASE =====
let data = {};
if (fs.existsSync("data.json")) {
  data = JSON.parse(fs.readFileSync("data.json"));
}

function save() {
  fs.writeFileSync("data.json", JSON.stringify(data, null, 2));
}

function getUser(id) {
  if (!data[id]) {
    data[id] = {
      level: 1,
      xp: 0,
      memory: [],
      weakTopics: {}
    };
  }
  return data[id];
}

// ===== LEVEL SYSTEM =====
function checkLevel(user) {
  if (user.xp >= user.level * 100) {
    user.level++;
    user.xp = 0;
  }
}

// ===== DETECT TYPE =====
function detectType(input) {
  if (/[\dxyz\+\-\*\/\^\(\)]/.test(input)) return "math";
  if (input.toLowerCase().includes("quiz")) return "quiz";
  if (input.toLowerCase().includes("flashcard")) return "flashcard";
  return "ai";
}

// ===== MATH ENGINE =====
function solveMath(input) {
  try {
    const result = math.simplify(input).toString();
    return {
      answer: result,
      explanation: `Simplified using math engine`
    };
  } catch {
    return null;
  }
}

// ===== QUIZ =====
function makeQuiz(topic) {
  return {
    answer: `📚 Quiz: ${topic}`,
    explanation: `
1. What is ${topic}?
2. Give an example.
3. Explain why it is important.
`
  };
}

// ===== FLASHCARDS =====
function makeFlashcards(topic) {
  return {
    answer: `🧾 Flashcards: ${topic}`,
    explanation: `
Q: What is ${topic}?
A: [Definition]

Q: Key idea?
A: [Explanation]

Q: Example?
A: [Example]
`
  };
}

// ===== AI =====
async function askAI(prompt) {
  try {
    const res = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${OPENAI_API_KEY}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        messages: [
          {
            role: "system",
            content: `
You are an AI tutor.

Format EXACTLY:
Answer: <answer>

Explanation:
<explanation>

Be clear and simple.
            `
          },
          { role: "user", content: prompt }
        ]
      })
    });

    const json = await res.json();
    return json.choices?.[0]?.message?.content || "No response";
  } catch {
    return "AI error";
  }
}

// ===== MAIN ENGINE =====
async function engine(input, user) {
  const type = detectType(input);

  // ⚡ MATH
  if (type === "math") {
    const res = solveMath(input);
    if (res) return res;
  }

  // 📚 QUIZ
  if (type === "quiz") {
    const topic = input.replace("quiz", "").trim();
    return makeQuiz(topic);
  }

  // 🧾 FLASHCARDS
  if (type === "flashcard") {
    const topic = input.replace("flashcard", "").trim();
    return makeFlashcards(topic);
  }

  // 🧠 AI
  const ai = await askAI(input);

  return {
    answer: ai,
    explanation: "Generated by AI"
  };
}

// ===== COMMAND =====
const commands = [
  new SlashCommandBuilder()
    .setName("ask")
    .setDescription("Ask anything")
    .addStringOption(o =>
      o.setName("question")
        .setDescription("Your question")
        .setRequired(true)
    )
].map(c => c.toJSON());

// REGISTER
const rest = new REST({ version: "10" }).setToken(TOKEN);
(async () => {
  await rest.put(Routes.applicationCommands(CLIENT_ID), { body: commands });
})();

// ===== HANDLER =====
client.on("interactionCreate", async interaction => {
  if (!interaction.isChatInputCommand()) return;

  const user = getUser(interaction.user.id);

  if (interaction.commandName === "ask") {
    const question = interaction.options.getString("question");

    await interaction.deferReply();

    const result = await engine(question, user);

    user.memory.push({ role: "user", content: question });
    user.memory.push({ role: "assistant", content: result.answer });

    user.xp += 10;
    checkLevel(user);

    save();

    return interaction.editReply(
      `🧠 Answer: ${result.answer}\n\n📖 Explanation:\n${result.explanation}`
    );
  }
});

client.login(TOKEN);